### ISSUE TITLE
Any way to replicate encryption in Python?

### ISSUE THREAD

**Issue by JediKnightChan** [maxenko/SodiumUE4#6]
Wanted to replicate encryption, logged out buffer as a hex string (String to Bytes is really weird implementation), tried to use aes mode_ecb in Crypto.Cypher, never got the same result. In the UE, the encryption result can even change with time! But it usually stays the same, in most frequent form.

**Comment by maxenko** [comment]
@JediKnightChan I have not intended this to be used in the editor with python if thats what you're looking for.
This plugin is overdue for an update anyway to UE 4.27 and 5.2 I will look into it as time allows.

Bytes is what Sodium expects, it doesn't work directly with strings afaik, so that's why example converts to bytes. There can certainly be utility functions added to hide that step.
